name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # كل يوم
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: https://github.com/youssefelmesedy
          outputs: |
            ./output/snake.svg
            ./output/snake-dark.svg
          color_snake: '#00FFEF'
          color_dots: '#111111,#222222,#333333,#444444,#38BDF8'
          background_color: '#000000'
      - name: Push the generated files
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update GitHub contribution snake"
