name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # كل يوم الساعة 12 منتصف الليل
  workflow_dispatch:     # تقدر تشغله يدويًا من Actions

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: youssefelmesedy
          outputs: |
            ./output/snake.svg
            ./output/snake-dark.svg

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./output
